# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "debian/buster64"

  # Give a proper hostname to the box
  config.vm.hostname = "covid19-develop"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.84"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true

    # Change the network cards to VirtIO for better performance:
    # Two network cards since I also have a host-only network.
    vb.customize ["modifyvm", :id, '--nictype1', 'virtio']
    vb.customize ["modifyvm", :id, '--nictype2', 'virtio']

    # Customize the amount of memory on the VM:
    vb.memory = "512"
   end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Will copy webfs config and .gitconfig to the vm.
  config.vm.provision "file", source: "./webfsd.conf", destination: "~/webfsd.conf"
  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL
    # Update repositiories before installing anything.
    apt-get update

    # Update system to latest packages.
    DEBIAN_FRONTEND=noninteractive apt-get --yes dist-upgrade

    # Then install the basic packages that we need to work comfortably.
    DEBIAN_FRONTEND=noninteractive apt-get install --yes vim git screen ncftp mc build-essential linux-headers-amd64 curl webfs

    # Downloading and installing things have ended, clean the downloaded packages.
    apt-get clean

    # Install the node 12.x from NodeSoruce binary distribution.
    curl -sL https://deb.nodesource.com/setup_12.x | bash -
    apt-get install --yes nodejs

    # Lastly, get the source code that we're gonna work with.
    sudo --user=vagrant sh -c 'mkdir git && cd git && git clone https://github.com/hbayindir/covid-19-turkey.git && cd covid-19-turkey && npm install axios'

    # Move the webfs config file to its correct place.
    mv --verbose  ~vagrant/webfsd.conf /etc/webfsd.conf
    chown --verbose root:root /etc/webfsd.conf
  SHELL

  config.vm.post_up_message = "Your development VM is ready. If you've just porivisioned the VM, due to a problem in webfs start/stop scripts, please restart your VM with vagrant reload to make new webfs settings take effect, thank you."
end
